name-template: "Teams but (actually) good v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
version-template: "$MAJOR.$MINOR.$PATCH"
change-template: "- $TITLE (#$NUMBER)"
no-changes-template: "* No changes"
category-template: "## $TITLE"
categories:
  - title: "🚀 Features"
    labels: ["feat", "feature", "enhancement"]
    collapse-after: 5
  - title: "🐛 Bug Fixes"
    labels: ["fix", "bug", "hotfix"]
    collapse-after: 5
  - title: "🧹 Maintenance"
    labels:
      ["chore", "docs", "refactor", "ci", "build", "test", "style", "deps"]
    collapse-after: 5
autolabeler:
  - label: "feat"
    title:
      - '/^feat(\(.+\))?:/i'
      - '/^feature(\(.+\))?:/i'
  - label: "fix"
    title:
      - '/^fix(\(.+\))?:/i'
      - '/^bug(\(.+\))?:/i'
      - '/^hotfix(\(.+\))?:/i'
  - label: "chore"
    title:
      - '/^chore(\(.+\))?:/i'
      - '/^docs(\(.+\))?:/i'
      - '/^refactor(\(.+\))?:/i'
      - '/^build(\(.+\))?:/i'
      - '/^ci(\(.+\))?:/i'
      - '/^test(\(.+\))?:/i'
      - '/^style(\(.+\))?:/i'
      - '/^deps(\(.+\))?:/i'
template: |
  ## What's Changed
  $CHANGES

version-resolver:
  major:
    labels:
      - "breaking"
  minor:
    labels:
      - "feature"
      - "enhancement"
  patch:
    labels:
      - "bug"
      - "fix"
      - "chore"
  default: patch
