name: Feature request
description: Request an enhancement for Teams but (actually) good
assignees: ["LeonimusTTV"]
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: "Problem"
      description: "Describe the problem to be solved."
      placeholder: "The Teams chat sidebar is too narrow. It makes it difficult to..."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Expected behavior"
      description: "Describe what the new feature or behavior would look like. How does it solve the problem?"
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: "Agreements"
      description: "Check the following before submitting the feature request."
      options:
        - label: "My title is concise but descriptive and specific."
          required: true
        - label: "I am on the latest Teams but (actually) good release."
          required: true
        - label: "I have searched for [existing feature requests](https://github.com/LeonimusTTV/teams-but-actually-good/issues?q=is:issue%20label:enhancement%20)."
          required: true
        - label: "This is not a usage or 'How to' question."
          required: true
