// Auto-generated file - do not edit manually
// Generated by scripts/generate-all.ts

import settingsplugin from "../teams-plugins/settings";
import betterAppBarplugin from "../teams-plugins/betterAppBar";
import statusplugin from "../teams-plugins/status";
import gifsplugin from "../teams-plugins/gifs";
import telemetryplugin from "../teams-plugins/telemetry";
import inputBarCleanerplugin from "../teams-plugins/inputBarCleaner";

export const plugins = [
  settingsplugin,
  betterAppBarplugin,
  statusplugin,
  gifsplugin,
  telemetryplugin,
  inputBarCleanerplugin
];
