// Auto-generated file - do not edit manually
// Generated by scripts/generate-all.ts

import settingsplugin from "../teams-plugin/settings";
import betterAppBarplugin from "../teams-plugin/betterAppBar";
import statusplugin from "../teams-plugin/status";
import gifsplugin from "../teams-plugin/gifs";
import telemetryplugin from "../teams-plugin/telemetry";
import inputBarCleanerplugin from "../teams-plugin/inputBarCleaner";

export const plugins = [
  settingsplugin,
  betterAppBarplugin,
  statusplugin,
  gifsplugin,
  telemetryplugin,
  inputBarCleanerplugin
];
