// Auto-generated file - do not edit manually
// Generated by scripts/generate-plugins.ts

import settingsPlugin from "../teams-plugin/settings";
import testPlugin from "../teams-plugin/test";

export const plugins = [
  settingsPlugin,
  testPlugin
];
