// Auto-generated file - do not edit manually
// Generated by scripts/generate-all.ts

import testtheme from "../themes/test";
import test2theme from "../themes/test2";

export const themes = [
  testtheme,
  test2theme
];
