import path from "path";
import fs from "fs";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const pluginFolder = "teams-plugins";
const pluginDir = path.resolve(__dirname, `../src/${pluginFolder}`);
const pluginOutputFile = path.resolve(
  __dirname,
  "../src/utils/plugin-registry.ts",
);
const themeFolder = "themes";
const themeDir = path.resolve(__dirname, `../src/${themeFolder}`);
const themeOutputFile = path.resolve(
  __dirname,
  "../src/utils/theme-registry.ts",
);

export function generateAll(
  dir: string,
  outputFile: string,
  folderName: string,
  type: "plugin" | "theme",
) {
  try {
    const entries = fs.readdirSync(dir, { withFileTypes: true });

    const imports: string[] = [];
    const names: string[] = [];

    if (type === "plugin") {
      const folders = entries.filter((entry) => entry.isDirectory());

      for (const folder of folders) {
        const folderPath = path.join(dir, folder.name);

        // Look for index file
        const indexFile = ["index.ts", "index.tsx"].find((file) =>
          fs.existsSync(path.join(folderPath, file)),
        );

        if (!indexFile) {
          console.warn(`No index file found in ${folder.name}, skipping...`);
          continue;
        }

        // Generate safe variable name from folder name
        const varName = folder.name
          .replace(/[^a-zA-Z0-9]/g, "_")
          .replace(/^(\d)/, "_$1");

        imports.push(
          `import ${varName}${type} from "../${folderName}/${folder.name}";`,
        );
        names.push(`${varName}${type}`);
      }
    } else {
      const themeFiles = entries.filter(
        (entry) => entry.isFile() && /\.(css|scss)$/i.test(entry.name),
      );

      for (const file of themeFiles) {
        const fileNameWithoutExt = file.name.replace(/\.[^.]+$/, "");
        const varName = fileNameWithoutExt
          .replace(/[^a-zA-Z0-9]/g, "_")
          .replace(/^(\d)/, "_$1");

        imports.push(
          `import ${varName}${type} from "../${folderName}/${file.name}";`,
        );
        names.push(`${varName}${type}`);
      }
    }

    // Generate the file content
    const content = `// Auto-generated file - do not edit manually
// Generated by scripts/generate-all.ts

${imports.join("\n")}

export const ${type === "plugin" ? "plugins" : "themes"} = [
  ${names.join(",\n  ")}
];
`;

    fs.writeFileSync(outputFile, content, "utf-8");
    console.log(
      `✓ Generated ${type} registry with ${names.length} ${type === "plugin" ? "plugins" : "themes"}`,
    );
    return true;
  } catch (error) {
    console.error(`Error generating ${type} registry:`, error);
    return false;
  }
}

async function main() {
  await generateAll(pluginDir, pluginOutputFile, pluginFolder, "plugin");
  await generateAll(themeDir, themeOutputFile, themeFolder, "theme");
}

main();
