// Build-time script to generate plugin imports
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const pluginDir = path.resolve(__dirname, "../src/teams-plugin");
const outputFile = path.resolve(__dirname, "../src/utils/plugin-registry.ts");

function generatePluginRegistry() {
  try {
    const entries = fs.readdirSync(pluginDir, { withFileTypes: true });
    const folders = entries.filter((entry) => entry.isDirectory());

    const imports: string[] = [];
    const pluginNames: string[] = [];

    for (const folder of folders) {
      const folderPath = path.join(pluginDir, folder.name);

      // Look for index file
      const indexFiles = ["index.ts", "index.tsx"].find((file) =>
        fs.existsSync(path.join(folderPath, file)),
      );

      if (!indexFiles) {
        console.warn(`No index file found in ${folder.name}, skipping...`);
        continue;
      }

      // Generate safe variable name from folder name
      const varName = folder.name
        .replace(/[^a-zA-Z0-9]/g, "_")
        .replace(/^(\d)/, "_$1");

      imports.push(
        `import ${varName}Plugin from "../teams-plugin/${folder.name}";`,
      );
      pluginNames.push(`${varName}Plugin`);
    }

    // Generate the file content
    const content = `// Auto-generated file - do not edit manually
// Generated by scripts/generate-plugins.ts

${imports.join("\n")}

export const plugins = [
  ${pluginNames.join(",\n  ")}
];
`;

    fs.writeFileSync(outputFile, content, "utf-8");
    console.log(
      `✓ Generated plugin registry with ${pluginNames.length} plugins`,
    );
    return true;
  } catch (error) {
    console.error("Error generating plugin registry:", error);
    return false;
  }
}

generatePluginRegistry();
